dist: trusty
language: python
group: edge

python:
  - "3.6"
services:
  - redis-server

addons:
  apt:
    packages:
      - docker-ce
      - python3-setuptools
      - python3-pip

install:
  - pip install -r requirements.txt
  - pip install ./package[celery]

script:
  - cd tests
  - celery -A crud worker --loglevel=info --config celeryconfig
  - python test_ep_persistence.py
