dist: trusty
language: python
group: edge

python:
  - "3.6"
services:
  - redis-server
#  - docker

addons:
  apt:
    packages:
      - docker-ce
      - python3-setuptools
      - python3-pip

install:
  - pip install -r requirements.txt
  - pip install ./package[celery]

script:
  - celery -A crud worker --loglevel=info --config tests/celeryconfig
  - pytest